require('./1')
require('./2')
require('./BRC')
require('./HiddenPair')
require('./import')
require('./index')
require('./NakedPair')
require('./NakedTriple')
require('./RBC')
require('./rectangles')
require('./Steinbutt')
require('./ThirdEye')
require('./Versteckter Single 2')
require('./Versteckter Single')
require('./WWing')
require('./X Wing')
require('./XChain')
require('./XYWing')
export default {}