name: Deploy to Dockerhub

on:
  push:
    branches: [ main ]
    paths: 
      - Dockerfile
      - src/**
      - public/**
      - package.json
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    
    - name: Build & Publish Container
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: ${{ secrets.DOCKER_USERNAME }}/sudoku