name: Deploy to Dockerhub

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - Dockerfile
      - src/**
      - public/**
      - package.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch

      - name: Build & Publish Container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: ${{ secrets.DOCKER_USERNAME }}/sudoku
          push_image_and_stages: ${{ steps.branch.outputs.branch == 'main' }}
